name: phimote
description: An unofficial Philips TV remote control app.

publish_to: 'none'

version: 0.5.2+7

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  shared_preferences: ^2.0.5
  http: ^0.13.1
  http_auth: ^1.0.0
  json_annotation: ^4.0.1
  ping_discover_network: ^0.2.0+1
  material_search: ^0.2.8
  flutter_vibrate: ^1.0.0
  cached_network_image: ^2.4.1
  provider: ^5.0.0
  upnp: ^2.0.0+1
  get_it: ^6.0.0
  freezed_annotation: ^0.14.1
  flutter_platform_widgets: ^0.80.1
  flutter_mailer: ^1.0.1
  connectivity: ^3.0.3
  in_app_review: ^2.0.1
  url_launcher: ^6.0.2
  package_info: ^2.0.0
  wakelock: ^0.5.0+2
  smooth_page_indicator: ^0.2.0
  flutter_launcher_icons: #^0.8.1
    git:
      url: git@github.com:zierka/flutter_launcher_icons.git
      ref: scaling
  path_provider: ^2.0.1
  let_log: ^1.1.4
  shake: ^1.0.0
  flutuate_mixpanel: ^1.1.8

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^4.0.2
  freezed: ^0.14.1
  pigeon: ^0.1.9

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/available_commands.json

flutter_icons:
  ios: "AppIcon"
  android: "ic_launcher"
  image_path_ios: "lib/assets/app_icon_ios.png"
  image_path_android: "lib/assets/app_icon_android.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "lib/assets/app_icon_android.png"
  adaptive_icon_foreground_scale_factor: 0.6
  # adaptive_icon_foreground_scale_fill_color: "#FFFFFFFF" #probably not needed as default is fill transparent