name: phimote
description: An unofficial Philips TV remote control app.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  shared_preferences: ^2.0.15
  http: ^0.13.5
  http_auth: ^1.0.1
  json_annotation: ^4.7.0
  ping_discover_network: #^0.2.0+1
    git:
      url: git@github.com:deakjahn/ping_discover_network.git
  # material_search: ^0.2.8
  flutter_vibrate: #^1.0.0
    git:
      url: git@github.com:AugustToko/flutter_vibrate.git
  cached_network_image: ^3.2.2
  provider: ^6.0.4
  upnp: #^2.0.0+1
    git:
      url: git@github.com:thecoda/upnp.dart.git

  # multicast_dns: ^0.3.2+2
  network_tools: ^3.0.0+3
  dart_ping_ios: ^2.0.1

  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  flutter_platform_widgets: ^2.0.0
  flutter_mailer: ^2.0.1
  connectivity: ^3.0.6
  in_app_review: ^2.0.4
  url_launcher: ^6.1.6
  package_info: ^2.0.2
  wakelock: ^0.6.2
  smooth_page_indicator: ^1.0.0+2
  flutter_launcher_icons: ^0.10.0
    # git:
    #   url: git@github.com:zierka/flutter_launcher_icons.git
    #   ref: scaling
  path_provider: ^2.0.11
  let_log: ^1.1.4
  shake: ^2.1.0
  # flutuate_mixpanel: ^1.1.8

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.1.0+1
  pigeon: ^4.2.5

  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/available_commands.json

flutter_icons:
  ios: "AppIcon"
  android: "ic_launcher"
  image_path_ios: "lib/assets/app_icon_ios.png"
  image_path_android: "lib/assets/app_icon_android.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "lib/assets/app_icon_android.png"
  adaptive_icon_foreground_scale_factor: 0.6
  # adaptive_icon_foreground_scale_fill_color: "#FFFFFFFF" #probably not needed as default is fill transparent