name: phimote
description: An unofficial Philips TV remote control app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.3+4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  shared_preferences: ^0.5.4+3
  http: ^0.12.0+2
  http_auth: ^0.3.0
  json_annotation: ^3.0.1
  ping_discover_network: ^0.2.0+1
  material_search: ^0.2.8
  flutter_vibrate: ^1.0.0
  cached_network_image: ^2.0.0
  provider: ^4.0.4
  upnp: ^2.0.0+1
  get_it: ^5.0.1
  freezed_annotation: ^0.12.0
  flutter_platform_widgets: ^0.71.0

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^3.3.0
  freezed: ^0.12.1
  pigeon: ^0.1.9

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/available_commands.json
    