# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    app_store_connect_api_key(
    )
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    sh("security find-identity -v -p codesigning")

    # increment_build_number(xcodeproj: "Runner.xcodeproj")
    match(
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
    
    upload_to_testflight

    delete_temp_keychain
  end

  def delete_temp_keychain(name)
    delete_keychain(
      name: name
    ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  end
  
  def create_temp_keychain(name, password)
    create_keychain(
      name: name,
      password: password,
      unlock: false,
      timeout: false
    )
  end
  
  def ensure_temp_keychain(name, password)
    delete_temp_keychain(name)
    create_temp_keychain(name, password)
  end
end
